name: CI-CD Workflow

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      deployment: false
    env:
      ENV_NAME: ${{ vars.ENV_NAME }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
      BUCKET_NAME: ${{ vars.BUCKET_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_TYPE: ${{ vars.DB_TYPE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.0.0
        with:
          activate-environment: true

      - name: Install dependencies
        run: uv sync --dev --extra postgres

      - name: Start development containers
        run: docker compose -f ./docker/dev/compose.yml up -d
          
      - name: Test python pipeline
        run: pytest tests/

      - name: Test dbt transformation
        run: |
          prefect server start --background
          python -m py_pipeline.orchestration

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    environment:
      name: prod
    env:
      ENV_NAME: ${{ vars.ENV_NAME }}
      S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
      BUCKET_NAME: ${{ vars.BUCKET_NAME }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_TYPE: ${{ vars.DB_TYPE }}
      PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.0.0
        with:
          activate-environment: true

      - name: Install dependencies
        run: uv sync --no-dev --extra snowflake

      - name: Generate requirements.txt for managed pool
        run: >
          uv export --format requirements.txt --no-dev --extra snowflake 
          --no-hashes --no-header --no-annotate --no-editable --no-emit-project -o requirements.txt

      - name: Deploy to prefect cloud
        run: prefect deploy --no-prompt --all --prefect-file prefect.cloud.yaml
        

      

      
      

          
